### ISSUE TITLE
Plugin fails to load. Inventree API changed?

### ISSUE THREAD

**Issue by ghost** [wolflu05/inventree-cups-plugin#13]
Hi,

the Plugin does not load anymore the following error message is displayed instead on the Plugins page:

```
discovery	/root/.local/lib/python3.11/site-packages/inventree_cups/cups_plugin.py	cannot import name 'LabelTemplate' from 'report.models' (/home/inventree/src/backend/InvenTree/report/models.py)
```

replacing `from report.models import LabelTemplate` with `from label.models import LabelTemplate` (found the `LabelTemplate` class in `/src/backend/InvenTree/label/models.py`) fixes the Error message but the Plugin is still not loaded/usable.

it seems that inventree has changed its API.

Best Regards
Christoph Russow

**Comment by wolflu05** [comment]
Hi Christoph,

yes, InvenTree changed its label printing API with 0.16 (and also enabled the machine interface introduced by 0.14 for production use, see [docs](https://docs.inventree.org/en/latest/extend/machines/label_printer/#label-printer), this adds the ability to connect multiple printers using the same plugin). This plugin in version 1.0.0 will only be compatible with inventree>=0.16. If you're running a lower version (current stable) you need to use this plugin in version 0.1.0 as stated in the readme, or wait until inventree 0.16 is released (should be in a few weeks according to the milestone date).

Hope that helps.
Best regards
Lukas

**Comment by ghost** [comment]
Hi Lukas,

ok thanks that helps yes. 
can you hint me to how i install the 0.1.0 version (im running a docker setup with the `docker-compose.yml` and `Dockerfile` from the `readme.md`)

Best Regards
Christoph

**Comment by wolflu05** [comment]
How have you installed this plugin in the first place? 

Easiest will be to just use the UI and enter a version specifier like so:
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/de45739a-db18-4adf-a0d8-6f7c83f0f971">

**Comment by wolflu05** [comment]
Simply add a version specifier to the instructions from the readme (I just found out, that this references the installation using git, this should be changed to use the provided pypi package):

```diff
ARG INVENTREE_TAG

# prebuild stage - needs a lot of build dependencies
FROM python:3.11-alpine3.18 as prebuild

RUN apk add --no-cache cups-dev gcc git musl-dev && \
-    pip install --user --no-cache-dir git+https://github.com/wolflu05/inventree-cups-plugin
+    pip install --user --no-cache-dir inventree-cups-plugin==0.1.0

# production image - only install the cups shared library
FROM inventree/inventree:${INVENTREE_TAG} as production

RUN apk add --no-cache cups-libs
COPY --from=prebuild /root/.local /root/.local
```

**Comment by ghost** [comment]
i've installed it with the `Dockerfile` you specified within the `readme.md`

i think i got it by specifiying the `inventree-cups-plugin==0.1.0` instead of the URL.

but now i get:

```
discovery	/root/.local/lib/python3.11/site-packages/inventree_cups/cups_plugin.py	cannot import name 'ugettext_lazy' from 'django.utils.translation' (/root/.local/lib/python3.11/site-packages/django/utils/translation/__init__.py)
```

# Version Information:
InvenTree-Version: 0.15.8
Django Version: 4.2.14
Commit Hash: aed43b0
Commit Date: 2024-08-08

Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Platform: Linux-6.10.2-arch1-1-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

**Comment by wolflu05** [comment]
Oh, it seems like 0.1.0 is still to old for using with 0.15.8, due to some django api changes. I personally run the unstable version in production (which is not recommended) so I haven't noticed this issue. Then you need to modify the plugin yourself. Something like the following modification to the Dockerfile should work:

```diff
RUN apk add --no-cache cups-dev gcc git musl-dev && \
    pip install --user --no-cache-dir inventree-cups-plugin==0.1.0

+RUN sed -i 's/ugettext_lazy/gettext_lazy/g' /root/.local/lib/python3.11/site-packages/inventree_cups/cups_plugin.py

# production image - only install the cups shared library
FROM inventree/inventree:${INVENTREE_TAG} as production
```

**Comment by wolflu05** [comment]
@codeaddicted Did this work for you until 0.16 is released?

**Comment by ghost** [comment]
sorry. forgot to confirm. yes indeed this worked like a charm.

**Comment by wolflu05** [comment]
Ok, so we can close this now?

**Comment by ghost** [comment]
absolutely
