### ISSUE TITLE
Not showing up in Settings

### ISSUE THREAD

**Issue by jpeg2600** [wolflu05/inventree-cups-plugin#14]
Hi there 

The plugin shows up in the "Plugins" list, it seems like it's successfully activated but there's nothing showing up in the sidebar. 

I'm using InvenTree 0.16.8.

Any idea?

**Comment by jpeg2600** [comment]
I understood that I had to go in the new UI and add a machine using the CUPS driver, but there seems to be no settings :
![image](https://github.com/user-attachments/assets/c7b8fbaa-3cbb-4386-a2d8-aff4ef57094c)

There's something I'm missing out here.

**Comment by jpeg2600** [comment]
I reinstalled everything and I have the driver settings now. It would be awesome if I could use that driver to send raw ZPL to my CUPS printer. 

![image](https://github.com/user-attachments/assets/dec22f9b-f546-4dba-81b3-232eb3347a54)

**Comment by wolflu05** [comment]
There may be showing nothing up when changin the `PRINTER` setting, because your host is wrong. `localhost` here refers to the docker containers IP, you may want to reference your host, for that just enter the hosts IP.
