### ISSUE TITLE
Labels could not be generated

### ISSUE THREAD

**Issue by jpeg2600** [wolflu05/inventree-cups-plugin#15]
Hi there, 

I successfully added my label printer to CUPS and can print test pages from there. I also added the printer to the CUPS plugin and it's correctly initialized. 

However, when it comes to print from Inventree, I get the error "Labels could not be generated". Any idea?  

I'm using inventree 0.16.8

![image](https://github.com/user-attachments/assets/b45a5497-a176-49cb-a7ad-25d3095e1901)

![image](https://github.com/user-attachments/assets/45b872bd-11bb-42dd-8969-9d4295d0ff9f)

![image](https://github.com/user-attachments/assets/2647904b-d1c7-41eb-a0b1-0267b71ef582)

**Comment by wolflu05** [comment]
This is not related to the plugin itself. Regarding using this for zebra printers, I would suggest using https://inventree.org/SergeoLacruz/inventree-zebra-plugin for printing (the machine integration there is not yet implemented)

(And this error you see is currently expected as status polling for asynchronous printing is not yet implemented, but instead shows such a message. However printing works just fine. This has come up several times, I created an issue for it now: https://github.com/inventree/InvenTree/issues/8511)

**Comment by jpeg2600** [comment]
Ok thanks a lot! 

I tried running the Zebra plugin but couldn't manage to get it installed correctly. I'll give it another go now that I can send RAW commands to my printer.

**Comment by jpeg2600** [comment]
@wolflu05 I got it to work using the Zebra plugin, thanks for the support and great work!

**Comment by wolflu05** [comment]
Nice that you got it working 👍 , glad to help.
