### ISSUE TITLE
Plugin installed but not visible in GUI

### ISSUE THREAD

**Issue by ghost** [wolflu05/inventree-cups-plugin#3]
Hi,

i have a new bare metal installation of inventree and tried to install the plugin via the gui. it is added to the plugins.txt file

```
# InvenTree Plugins (uses PIP framework to install)
inventree-cups-plugin@git+https://github.com/wolflu05/inventree-cups-plugin  # Installed 2023-06-25 14:53:03.629288+00:00 by admin
```

but it is not visible in the plugin settings neither in the sidemenue nor in the list of installed plugins. i restarted the system several times to no avail.

according to the startup log everything went well.

```
Jun 25 17:09:37 inventree inventree-web-1.service[1664]: Collecting inventree-cups-plugin@ git+https://github.com/wolflu05/inventree-cups-plugin
Jun 25 17:09:37 inventree inventree-web-1.service[1664]:   Cloning https://github.com/wolflu05/inventree-cups-plugin to /tmp/pip-install-08ewvyre/inventree-cups-plugin_3134e7ad0f5540008d961379df2730a6
Jun 25 17:09:37 inventree inventree-web-1.service[1664]:   Resolved https://github.com/wolflu05/inventree-cups-plugin to commit e22e825507b6355d9d35cd286ebff0d13b79ef88
Jun 25 17:09:37 inventree inventree-web-1.service[1664]:   Preparing metadata (setup.py): started
Jun 25 17:09:37 inventree inventree-web-1.service[1664]:   Preparing metadata (setup.py): finished with status 'done'
Jun 25 17:09:37 inventree inventree-web-1.service[1664]: Requirement already satisfied: pycups in ./.heroku/python/lib/python3.10/site-packages (from inventree-cups-plugin@ git+https://github.com/wolflu05/inventree-cups-plugin->-r /etc/inventree/plugins.txt (line 2)) (2.0.1)
```

```
# Version Information:
InvenTree-Version: 0.11.2
Django Version: 3.2.18


Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]
```

the system was installed with the installer script

any help is apreciated.

if you need more infos don't hesitate to ask.

Best Regards
Christoph

**Comment by ghost** [comment]
ok now i got a little further. i cloned the git repo into `/opt/inventree/InvenTree/plugins` and linked the inventree_cups directory there (`ln -s inventree-cups-plugin/inventree_cups`) now i got 
![Bildschirmfoto_2023-06-25_19-28-08](https://github.com/wolflu05/inventree-cups-plugin/assets/2549755/985c49d7-6805-44dc-a2d0-e776a85a77e3)

i already installed the `pycups` module in the system python (`pip install pycups`) as well as the inventree virtenv `inventree run pip install pycups` and can see it in either `pip list` output (version `2.0.1`)

edit: executing `inventree run python` and typing `import cups<enter>` gives no error.

**Comment by ghost** [comment]
ok it seems i got it working. inventree in bare metal seems to rely on `/opt/inventree/env/bin/python` so in installed pycups with `/opt/inventree/env/bin/pip install pycups` and the plugin appeared and i could enable it.

**Comment by ghost** [comment]
closing solved.

**Comment by wolflu05** [comment]
Hello, good that you got it working now, but actually pycups should be installed automatically as dependency if you install my plugin as a pip package. Need to provide it via pypi in the future for easier and faster install instead of relying on git. The only thing that you need to install manually is the cups dev system package required for pycups

**Comment by ghost** [comment]
yeah the problem was that both installing it manually (plugin.txt) and installing it over the gui used the wrong python env (`/opt/inventree/.heroku/python/bin/*`) and not the one actually used for execution (`/opt/inventree/env/bin/`). so the dep `pycups` got autoinstalled but on the wrong env.
dunno why tho. think it might be a problem of my inventree setup. maybe if i've got enough time i investigate that further.
