### ISSUE TITLE
Installation problem with pycups

### ISSUE THREAD

**Issue by tnemrap** [wolflu05/inventree-cups-plugin#4]
When installing i get this error
`(env) inventree@astrid:~$ pip install git+https://github.com/wolflu05/inventree-cups-plugin
Collecting git+https://github.com/wolflu05/inventree-cups-plugin
  Cloning https://github.com/wolflu05/inventree-cups-plugin to /tmp/pip-req-build-lhgmgzyd
  Running command git clone --filter=blob:none --quiet https://github.com/wolflu05/inventree-cups-plugin /tmp/pip-req-blhgmgzyd
  Resolved https://github.com/wolflu05/inventree-cups-plugin to commit e22e825507b6355d9d35cd286ebff0d13b79ef88
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycups (from inventree-cups-plugin==0.1.0)
  Downloading pycups-2.0.1.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: inventree-cups-plugin, pycups
  Building wheel for inventree-cups-plugin (pyproject.toml) ... done
  Created wheel for inventree-cups-plugin: filename=inventree_cups_plugin-0.1.0-py3-none-any.whl size=4837 sha256=f325dd0ec4dcbca03622c53dd3c4638c893779a0010f3bf30b0dca2a505
  Stored in directory: /tmp/pip-ephem-wheel-cache-hbx9k6s1/wheels/10/10/e2/ad282e09f8a03e111e0fd4d5d7214f7c327f2a11e7b84
  Building wheel for pycups (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycups (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      In file included from cupsconnection.c:22:
      cupsconnection.h:26:10: fatal error: cups/http.h: No such file or directory
         26 | #include <cups/http.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycups
Successfully built inventree-cups-plugin
Failed to build pycups
ERROR: Could not build wheels for pycups, which is required to install pyproject.toml-based projects
(env) inventree@astrid:~$

`

**Comment by wolflu05** [comment]
Hello @tnemrap ,

this is because the native dependencies for cups are not installed. There is a warning in the README.md about that. So just install them before and then retry.

> ⚠️ This plugin needs `cups-devel` installed to install its dependencies. You can read more about the requirements at [pycups](https://github.com/OpenPrinting/pycups). If you're using apt as a package manager run `apt install libcups2-dev` before.

**Comment by tnemrap** [comment]
Thanks this is solved.
