### ISSUE TITLE
Installation problem with pycups within docker

### ISSUE THREAD

**Issue by ghost** [wolflu05/inventree-cups-plugin#5]
Hi,

i've got a similar problem to #4 but im running within docker (installed after the docker prod manual https://docs.inventree.org/en/latest/start/docker_prod ).

i get the following error 

```
inventree-worker  |   × Running setup.py install for pycups did not run successfully.
inventree-worker  |   │ exit code: 1
inventree-worker  |   ╰─> [8 lines of output]
inventree-worker  |       /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
inventree-worker  |         warnings.warn(
inventree-worker  |       In file included from cupsconnection.c:22:
inventree-worker  |       cupsconnection.h:26:10: fatal error: cups/http.h: No such file or directory
inventree-worker  |          26 | #include <cups/http.h>
inventree-worker  |             |          ^~~~~~~~~~~~~
inventree-worker  |       compilation terminated.
inventree-worker  |       error: command '/usr/bin/gcc' failed with exit code 1
inventree-worker  |       [end of output]
```

i already installed the libcups headers packet

```
root@ ~/docker-containers/inventree # pacman -Ss libcups
extra/libcups 1:2.4.7-1 [Installiert]
    OpenPrinting CUPS - client libraries and headers
```

and the file exists in the root filesystem

```
root@peter ~/docker-containers/inventree # ls /usr/include/cups/http.h -lah
-r--r--r-- 1 root root 31K 20. Sep 15:52 /usr/include/cups/http.h
```

how do i get it into my docker container so the plugin can be installed via `plugins.txt` ?

**Comment by wolflu05** [comment]
The cups headers need to be available in the docker container. So you would need to exec into the container and install them there. However if you recreate the container they would be lost, so the easiest way would be to create your own image using a Dockerfile like so:
```Dockerfile
FROM inventree/inventree

RUN apt install libcups2-dev 
```

then if you're using docker-compose, you can link that dockerfile like so to your inventree service, but make sure, you're using it for the worker and the server service.

```yml
    # image: inventree/inventree  # (commented out now)
    build: ./Dockerfile
```

### Edit 

> [!NOTE]
> I added some docker instructions for inventree >= 0.13 to the [Readme](https://github.com/wolflu05/inventree-cups-plugin#docker)

**Comment by ghost** [comment]
awesome that worked thank you!

**Comment by wolflu05** [comment]
Great that you got it working 👍
